# permissions for end users to edit httproutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httproute-editor-role
rules:
- apiGroups:
  - proxy.bocloud.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.bocloud.io
  resources:
  - httproutes/status
  verbs:
  - get
