# permissions for end users to edit tcproutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tcproute-editor-role
rules:
- apiGroups:
  - proxy.bocloud.io
  resources:
  - tcproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.bocloud.io
  resources:
  - tcproutes/status
  verbs:
  - get
