# permissions for end users to view udproutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udproute-viewer-role
rules:
- apiGroups:
  - proxy.bocloud.io
  resources:
  - udproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.bocloud.io
  resources:
  - udproutes/status
  verbs:
  - get
