# permissions for end users to edit udproutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udproute-editor-role
rules:
- apiGroups:
  - proxy.bocloud.io
  resources:
  - udproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.bocloud.io
  resources:
  - udproutes/status
  verbs:
  - get
